### ISSUE TITLE
package crashed my server since a few hrs ago

### ISSUE THREAD

**Issue by Britnell** [storyblok/storyblok-astro#862] opened 2024-07-11 14:27 UTC
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-astro

[![storyblok.com](https://a.storyblok.com/f/88751/1500x500/7974d6bc34/storyblok-astro.png)][storyblokurl]

hope this is specific enough, but only happened on server.
saw an error during pipeline , and server was throwing completely, err 500

must have been most recent changes, was workign yesterday, and broke after my commit 2 hrs ago
---

## Expected Behavior

shouldnt crash and throw errors, useStoryblokApi() should return api object, not undefined

## Current Behavior

pipeline showed error `storyblokApiInstance has not been initialized correctly` , but i couldnt find anything about this 

server was throwing 500 
```
12:40:03 [ERROR] TypeError: Cannot read properties of undefined (reading 'get')...
```

in code : 
```
import { useStoryblokApi } from "@storyblok/astro";
const api = useStoryblokApi();
api.get("cdn/stories", { version })    // error thrown here
```

i couldnt check the package either, is hasn't worked for a while due to ts error `Cannot find module '@storyblok/astro' or its corresponding type declarations.ts(2307)` but it worked locally, so i assumed it was only missing types.
but i tried replaceing the package with storyblok-js-client , and that fixed it

```
import StoryblokClient from "storyblok-js-client";
const api = new StoryblokClient({
  accessToken:  '...',
});
api.get(...)
```

## Steps to Reproduce

1.
2.
3.

**Comment by dipankarmaikap** [comment] 2024-07-12 05:47
@Britnell Could you please provide the steps to reproduce the error? The "Steps to Reproduce" section is currently empty, and without that information, we cannot identify the cause or assist you with the error.

Thank you!

**Comment by Britnell** [comment] 2024-07-15 10:47
hey, yeah will do asap but on the road atm.

what can you say about the error log during build? i couldnt find where that comes from to debug

**Comment by dipankarmaikap** [comment] 2024-07-30 06:32
Hi @Britnell ,

Since we haven't received a response with the reproduction steps, we're unable to investigate further.

We'll close this issue for now. If you have new information or can provide the reproduction steps later, feel free to reopen it or create a new issue.

Thanks!

**Closed by dipankarmaikap** 2024-07-30 06:32 UTC
Labels: needs-reproduction
