### ISSUE TITLE
Indecipherable 404 errors

### ISSUE THREAD

**Issue by brightonmike** [storyblok/storyblok-astro#169] opened 2023-03-28 14:32 UTC
Error I'm getting:
```
▶ src/pages/[...slug].astro
 error   {"message":{},"status":404,"id":"src/pages/[...slug].astro"}
  Hint:
    To get as much information as possible from your errors, make sure to throw Error objects instead of `object`. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error for more information.
  Stacktrace:
Error: {"message":{},"status":404,"id":"src/pages/[...slug].astro"}
    at createSafeError (file:///Users/michael/Sites/meanwhile/node_modules/astro/dist/core/errors/utils.js:53:19)
    at throwAndExit (file:///Users/michael/Sites/meanwhile/node_modules/astro/dist/cli/index.js:225:52)
    at cli (file:///Users/michael/Sites/meanwhile/node_modules/astro/dist/cli/index.js:211:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

```

I know it's relating to content changes within Storyblok, but the error above gives us absolutely no information regarding where the problem lies. So debugging these errors is a huge time sink.

That these errors occur in the first place is very frustrating - we're unable to have _anything_ in Storyblok that we didn't add to the code base.

**Comment by Soviut** [comment] 2023-06-09 02:18
I ran in to something similar when I changed over to the publishing pipeline, rather than just retrieving drafts from the Storyblok API. The solution was two parts:

- Making sure that the environment variables were being imported correctly with `import.meta.env.SOME_VARIABLE` and not `process.env.SOME_VARIABLE`
- Using the "preview" API key with drafts (my staging deploy) and the "public" API key with published (my prod deploy).

**Comment by danny-goose** [comment] 2023-10-24 23:38
After pressing publish rather than save, the build worked... 
```
 src/pages/index.astro
  └─ /index.html (+525ms)
▶ src/pages/contact.astro
  └─ /contact/index.html (+61ms)
▶ src/pages/pricing.astro
  └─ /pricing/index.html (+5ms)
▶ src/pages/about.astro
  └─ /about/index.html (+9ms)
▶ src/pages/blog/[slug].astro
  ├─ /blog/blog-blog2/index.html (+429ms)
  └─ /blog/blog-blog1/index.html (+25ms)
▶ src/pages/blog.astro
 error   "{\"message\":\"Not Found\",\"status\":404,\"response\":\"This record could not be found\"}"
  Hint:
    To get as much information as possible from your errors, make sure to throw Error objects instead of `string`. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error for more information.
  File:
    /Users/danielisrael/Documents/astroship-main/node_modules/astro/dist/core/errors/utils.js:64:19
  Code:
    63 |   } else {
    > 64 |     const error = new Error(JSON.stringify(err));
         |                   ^
      65 |     error.hint = `To get as much information as possible from your errors, make sure to throw Error objects instead of \`${typeof err}\`. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error for more information.`;
      66 |     return error;
      67 |   }
  Stacktrace:
Error: "{\"message\":\"Not Found\",\"status\":404,\"response\":\"This record could not be found\"}"
    at createSafeError (file:///Users/danielisrael/Documents/astroship-main/node_modules/astro/dist/core/errors/utils.js:64:19)
    at throwAndExit (file:///Users/danielisrael/Documents/astroship-main/node_modules/astro/dist/cli/throw-and-exit.js:16:50)
    at cli (file:///Users/danielisrael/Documents/astroship-main/node_modules/astro/dist/cli/index.js:147:11)

**Comment by schabibi1** [comment] 2024-02-27 19:49
Hi, it's been a while since the last conversation has been active. I'll close this issue as I see some findings to solve. Please feel free to re-open this issue if you still need help with reproduction.

**Closed by schabibi1** 2024-02-27 19:49 UTC
Labels: dx, needs-reproduction

**Comment by vvaldesc** [comment] 2024-05-05 08:48
Similar error solved here: https://github.com/storyblok/storyblok-astro/issues/574

I get similar error too: https://github.com/storyblok/storyblok-astro/issues/800
